/**
 * Reads .env and writes src/environments/environment.ts + environment.development.ts.
 * Run automatically via the prestart / prebuild npm hooks.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';

if (!existsSync('.env')) {
  console.error('ERROR: .env file not found. Copy .env.example to .env and fill in your values.');
  process.exit(1);
}

const env = Object.fromEntries(
  readFileSync('.env', 'utf8')
    .split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.startsWith('#'))
    .map(l => {
      const idx = l.indexOf('=');
      return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()];
    })
);

const url = env['SUPABASE_URL'] ?? '';
const key = env['SUPABASE_ANON_KEY'] ?? '';

if (!url || !key) {
  console.error('ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set in .env');
  process.exit(1);
}

writeFileSync(
  'src/environments/environment.ts',
  `/** Production environment configuration — generated by scripts/generate-env.mjs. */
export const environment = {
  production: true,
  supabaseUrl: '${url}',
  supabasePublishableKey: '${key}',
};
`
);

writeFileSync(
  'src/environments/environment.development.ts',
  `/** Development environment configuration — generated by scripts/generate-env.mjs. */
export const environment = {
  production: false,
  supabaseUrl: '${url}',
  supabasePublishableKey: '${key}',
};
`
);

console.log('✓ environment files generated from .env');
